FROM node:14

# set up angular cli
RUN npm install -g @angular/cli

WORKDIR /app
COPY package.json /app
RUN npm install 
COPY . /app
CMD ng serve --host 0.0.0.0 --disable-host-check --proxy-config proxy.conf.dev.json
EXPOSE 4200